import type { CharacterData } from '../types';

// Every fighter uses the same simulation. Only data and small passive hooks differ.
export const CHARACTERS: CharacterData[] = [
  { id: 'kael', name: 'KAEL RIVEN', title: 'O fio do destino', weapon: 'sword', primary: '#243b50', secondary: '#15232f', accent: '#bd4a38', skin: '#c6ae91', outfit: 'coat', accessory: 'red-sash', description: 'Um duelista sem bandeira. Seu casaco carrega a poeira de caminhos que j\u00e1 n\u00e3o existem.', hp: 104, speed: 1, damage: 1, stamina: 100, stance: 0.08, spread: 31, idleSpeed: 1.8, idleAmount: 2.2, passive: { id: 'rhythm', name: 'Ritmo do duelista', description: 'O terceiro ataque leve custa 15% menos stamina.' }, ratings: [3, 3, 4] },
  { id: 'shiro', name: 'SHIRO VANE', title: 'O sil\u00eancio antes do corte', weapon: 'katana', primary: '#d1d0bd', secondary: '#414a46', accent: '#a98d74', skin: '#b8a28e', outfit: 'haori', accessory: 'broken-mask', description: 'Por tr\u00e1s da m\u00e1scara quebrada, nenhuma hesita\u00e7\u00e3o. Um corte basta para contar sua hist\u00f3ria.', hp: 96, speed: 1.025, damage: 1, stamina: 100, stance: 0.13, spread: 38, idleSpeed: 1.3, idleAmount: 1.4, passive: { id: 'stillness', name: 'Instante vazio', description: 'A janela de parry \u00e9 20 ms maior.' }, ratings: [5, 3, 2] },
  { id: 'nyx', name: 'NYX', title: 'Uma sombra a menos', weapon: 'dagger', primary: '#27252f', secondary: '#181c22', accent: '#9272b1', skin: '#b7a295', outfit: 'hood', accessory: 'purple-mask', description: 'Um capuz negro, duas l\u00e2minas e nenhum aviso. Quando a sombra se move, o duelo j\u00e1 come\u00e7ou.', hp: 94, speed: 1.055, damage: 0.98, stamina: 100, stance: 0.41, spread: 35, idleSpeed: 2.1, idleAmount: 1.7, passive: { id: 'shadow-step', name: 'Passo de sombra', description: 'Ataques leves causam 8% mais dano nos 600 ms ap\u00f3s uma esquiva.' }, ratings: [5, 1, 2] },
  { id: 'orin', name: 'ORIN KAST', title: 'Daqui, ningu\u00e9m passa', weapon: 'spear', primary: '#4c5f43', secondary: '#293b30', accent: '#b4a477', skin: '#c1ac8f', outfit: 'coat', accessory: 'single-pauldron', description: 'Seu sobretudo conhece todas as fronteiras. Sua lan\u00e7a conhece a dist\u00e2ncia exata para mant\u00ea-las.', hp: 105, speed: 0.97, damage: 1.01, stamina: 102, stance: 0.06, spread: 43, idleSpeed: 1.45, idleAmount: 1.8, passive: { id: 'control-zone', name: 'Zona de controle', description: 'Acertos distantes, al\u00e9m de 75% do alcance da arma, empurram 7% mais.' }, ratings: [2, 5, 3] },
  { id: 'bramm', name: 'BRAMM', title: 'A for\u00e7a tem um nome', weapon: 'axe', primary: '#79543b', secondary: '#3f3830', accent: '#b09864', skin: '#bd9a76', outfit: 'vest', accessory: 'huge-bracers', description: 'Colete de couro, bra\u00e7adeiras de ferro e a convic\u00e7\u00e3o de que toda guarda tem um limite.', hp: 111, speed: 0.93, damage: 1.035, stamina: 103, stance: 0.26, spread: 39, idleSpeed: 1.6, idleAmount: 3.3, passive: { id: 'iron-fist', name: 'Punho de ferro', description: 'Seus golpes causam 12% mais dano de stamina contra a guarda.' }, ratings: [1, 3, 4] },
  { id: 'raze', name: 'RAZE', title: 'Sem recuo', weapon: 'gauntlets', primary: '#a53c31', secondary: '#242829', accent: '#a9bab7', skin: '#b79679', outfit: 'jacket', accessory: 'metal-gloves', description: 'Criado nas ruas da forja. Nunca precisou de uma l\u00e2mina para deixar sua marca.', hp: 106, speed: 1.02, damage: 1.02, stamina: 102, stance: 0.2, spread: 36, idleSpeed: 3.6, idleAmount: 4, passive: { id: 'pressure', name: 'Sempre em frente', description: 'Recupera 18% mais stamina enquanto avan\u00e7a.' }, ratings: [5, 1, 3] },
  { id: 'vesper', name: 'VESPER', title: 'Eleg\u00e2ncia afiada', weapon: 'sword', primary: '#743747', secondary: '#29292c', accent: '#b9a285', skin: '#d1b7a3', outfit: 'coat', accessory: 'black-gloves', description: 'Seu sobretudo vinho nunca toca a poeira por acaso. Cada passo \u00e9 uma escolha; cada corte, uma assinatura.', hp: 100, speed: 1.01, damage: 0.99, stamina: 105, stance: -0.06, spread: 27, idleSpeed: 1.65, idleAmount: 1.3, passive: { id: 'elegant', name: 'Guarda elegante', description: 'Bloqueios frontais consomem 8% menos stamina.' }, ratings: [3, 3, 5] },
  { id: 'akari', name: 'AKARI', title: 'Uma linha vermelha', weapon: 'katana', primary: '#24282b', secondary: '#161e22', accent: '#c25343', skin: '#c8ae94', outfit: 'jacket', accessory: 'long-red-sash', description: 'Uma faixa vermelha corta o vento. Akari n\u00e3o busca o primeiro golpe, mas o golpe que importa.', hp: 97, speed: 1.045, damage: 1.015, stamina: 98, stance: 0.09, spread: 42, idleSpeed: 1.12, idleAmount: 1.1, passive: { id: 'serene', name: 'L\u00e2mina serena', description: 'Ataques iniciados com pelo menos 85% de stamina causam 6% mais dano.' }, ratings: [5, 3, 2] },
  { id: 'kiro', name: 'KIRO', title: 'O pre\u00e7o da sobreviv\u00eancia', weapon: 'dagger', primary: '#566052', secondary: '#2a342e', accent: '#b5a17a', skin: '#b69c7f', outfit: 'vest', accessory: 'mouth-mask', description: 'M\u00e1scara baixa, cintos apertados e sempre uma sa\u00edda. Um mercen\u00e1rio s\u00f3 recebe se voltar.', hp: 99, speed: 1.035, damage: 1.02, stamina: 99, stance: 0.32, spread: 30, idleSpeed: 2.4, idleAmount: 2.5, passive: { id: 'clean-exit', name: 'Sa\u00edda limpa', description: 'Esquivar custa 10% menos stamina por 800 ms depois de acertar um golpe.' }, ratings: [5, 1, 2] },
  { id: 'talos', name: 'TALOS', title: 'A \u00faltima sentinela', weapon: 'spear', primary: '#9f8e5b', secondary: '#3f4940', accent: '#ddc28a', skin: '#bba78b', outfit: 'armor', accessory: 'short-cape', description: 'Ouro gasto e uma capa curta. Sua vig\u00edlia continua muito depois que os port\u00f5es se fecharam.', hp: 108, speed: 0.945, damage: 0.99, stamina: 102, stance: -0.02, spread: 37, idleSpeed: 1.05, idleAmount: 1.2, passive: { id: 'sovereign', name: 'Ponta soberana', description: 'Sua lan\u00e7a possui 5% mais alcance f\u00edsico.' }, ratings: [2, 5, 4] },
  { id: 'garr', name: 'GARR', title: 'O inverno n\u00e3o vence', weapon: 'axe', primary: '#655642', secondary: '#3c3931', accent: '#a7a89a', skin: '#bca07e', outfit: 'fur', accessory: 'waist-chain', description: 'Pele sobre os ombros e correntes na cintura. Garr aprendeu com o frio a nunca ceder primeiro.', hp: 110, speed: 0.95, damage: 1.025, stamina: 101, stance: 0.35, spread: 44, idleSpeed: 1.9, idleAmount: 3.7, passive: { id: 'contained-fury', name: 'F\u00faria contida', description: 'Abaixo de 35% de vida, ataques pesados causam 6% mais dano.' }, ratings: [1, 3, 3] },
  { id: 'volt', name: 'VOLT', title: 'Antes do trov\u00e3o', weapon: 'gauntlets', primary: '#363e36', secondary: '#222d2a', accent: '#cbb24e', skin: '#ac8c70', outfit: 'vest', accessory: 'yellow-wraps', description: 'Bandagens amarelas escondem punhos inquietos. Seus passos chegam antes que o advers\u00e1rio termine de pensar.', hp: 97, speed: 1.07, damage: 0.98, stamina: 103, stance: 0.16, spread: 29, idleSpeed: 4.1, idleAmount: 3.6, passive: { id: 'live-charge', name: 'Carga viva', description: 'Sua velocidade de corrida \u00e9 6% maior.' }, ratings: [5, 1, 2] },
  { id: 'dante', name: 'DANTE KROSS', title: 'Nada a provar', weapon: 'sword', primary: '#272e2d', secondary: '#3c4541', accent: '#9ca39b', skin: '#bba289', outfit: 'coat', accessory: 'grey-scarf', description: 'Casaco aberto, len\u00e7o cinza e o olhar de quem j\u00e1 esteve aqui. A press\u00e3o s\u00f3 deixa sua m\u00e3o mais firme.', hp: 105, speed: 0.995, damage: 1.025, stamina: 97, stance: -0.04, spread: 33, idleSpeed: 1.55, idleAmount: 1.9, passive: { id: 'cold-blood', name: 'Sangue-frio', description: 'Recupera 12% mais stamina quando est\u00e1 abaixo de 40% de vida.' }, ratings: [3, 3, 4] },
  { id: 'rei', name: 'REI KAGAMI', title: 'O reflexo do a\u00e7o', weapon: 'katana', primary: '#466980', secondary: '#bbc4b9', accent: '#d8dec9', skin: '#c5ad93', outfit: 'haori', accessory: 'blue-white-haori', description: 'Azul e branco, tradi\u00e7\u00e3o e futuro. Rei encontra no ataque do advers\u00e1rio a abertura de que precisa.', hp: 99, speed: 1.01, damage: 0.99, stamina: 104, stance: 0.1, spread: 40, idleSpeed: 1.22, idleAmount: 1.5, passive: { id: 'steel-reflex', name: 'Reflexo de a\u00e7o', description: 'Um parry bem-sucedido recupera 5 pontos extras de stamina.' }, ratings: [4, 3, 3] },
  { id: 'moth', name: 'MOTH', title: 'Ningu\u00e9m por tr\u00e1s da m\u00e1scara', weapon: 'dagger', primary: '#a69c7d', secondary: '#4c5142', accent: '#d1c8a5', skin: '#ada18a', outfit: 'robes', accessory: 'insect-mask', description: 'Um manto rasgado atravessa a n\u00e9voa. Sob a m\u00e1scara de inseto, at\u00e9 a respira\u00e7\u00e3o parece emprestada.', hp: 96, speed: 1.02, damage: 1.025, stamina: 103, stance: 0.47, spread: 32, idleSpeed: 0.95, idleAmount: 2.8, passive: { id: 'elusive', name: 'Presen\u00e7a fugaz', description: 'Move-se cerca de 14% mais r\u00e1pido enquanto est\u00e1 agachado.' }, ratings: [4, 1, 2] },
  { id: 'sylva', name: 'SYLVA', title: 'O passo da ca\u00e7adora', weapon: 'spear', primary: '#4b6d4a', secondary: '#303f31', accent: '#aab58b', skin: '#bbab8d', outfit: 'cape', accessory: 'tall-boots', description: 'Capa verde, botas altas e pequenas placas de a\u00e7o. Para quem conhece a floresta, recuar tamb\u00e9m \u00e9 avan\u00e7ar.', hp: 99, speed: 1.035, damage: 0.995, stamina: 104, stance: 0.18, spread: 41, idleSpeed: 1.7, idleAmount: 2.1, passive: { id: 'hunter', name: 'P\u00e9s de ca\u00e7adora', description: 'Sua movimenta\u00e7\u00e3o para tr\u00e1s \u00e9 8% mais r\u00e1pida.' }, ratings: [3, 5, 3] },
  { id: 'drak', name: 'DRAK', title: 'Nenhuma segunda senten\u00e7a', weapon: 'axe', primary: '#343e3d', secondary: '#202a29', accent: '#939f91', skin: '#ad9b82', outfit: 'apron', accessory: 'iron-mask', description: 'A m\u00e1scara de ferro n\u00e3o julga. O avental escuro n\u00e3o esquece. Drak veio apenas terminar o trabalho.', hp: 109, speed: 0.925, damage: 1.04, stamina: 104, stance: 0.01, spread: 36, idleSpeed: 0.83, idleAmount: 1.6, passive: { id: 'sentence', name: 'Senten\u00e7a', description: 'Ataques pesados provocam 10% mais knockback.' }, ratings: [1, 3, 4] },
  { id: 'knuck', name: 'KNUCK', title: 'Mais um round', weapon: 'gauntlets', primary: '#b1703e', secondary: '#3b4843', accent: '#d4c3a0', skin: '#b79570', outfit: 'vest', accessory: 'wrapped-arms', description: 'Colete laranja, cal\u00e7a larga e punhos enfaixados. Seu melhor argumento sempre vem depois do terceiro golpe.', hp: 108, speed: 0.99, damage: 1.02, stamina: 104, stance: 0.28, spread: 40, idleSpeed: 3.2, idleAmount: 4.4, passive: { id: 'second-wind', name: 'Segundo f\u00f4lego', description: 'Acertar o quarto ataque de uma sequ\u00eancia leve devolve 4 de stamina.' }, ratings: [4, 1, 4] },
  { id: 'solen', name: 'SOLEN', title: 'A luz que permanece', weapon: 'sword', primary: '#c7ccb9', secondary: '#69756a', accent: '#c6ab70', skin: '#c6b39a', outfit: 'armor', accessory: 'short-cape', description: 'Armadura leve, detalhes dourados e uma capa branca que ainda resiste. H\u00e1 promessas que n\u00e3o se quebram.', hp: 106, speed: 0.985, damage: 0.98, stamina: 107, stance: -0.09, spread: 34, idleSpeed: 1.4, idleAmount: 1.65, passive: { id: 'tenacious', name: 'Luz tenaz', description: 'Recupera-se de um Guard Break 15% mais r\u00e1pido.' }, ratings: [3, 3, 5] },
  { id: 'yurei', name: 'YUREI', title: 'O que o vento deixou', weapon: 'katana', primary: '#8d9793', secondary: '#4a5856', accent: '#9fc6ca', skin: '#bec6b7', outfit: 'robes', accessory: 'pale-blue-sash', description: 'Roupas cinza, faixa azul-p\u00e1lida. Sua l\u00e2mina ocupa o espa\u00e7o que ele acabou de abandonar.', hp: 94, speed: 1.05, damage: 1.01, stamina: 101, stance: 0.035, spread: 35, idleSpeed: 0.9, idleAmount: 2.6, passive: { id: 'pale-breeze', name: 'Brisa p\u00e1lida', description: 'Sua esquiva termina 12% mais cedo, permitindo agir novamente.' }, ratings: [5, 3, 2] },
  { id: 'flick', name: 'FLICK', title: 'Aqui, agora n\u00e3o mais', weapon: 'dagger', primary: '#736748', secondary: '#394439', accent: '#c39d5d', skin: '#c2a582', outfit: 'scarf', accessory: 'forehead-goggles', description: '\u00d3culos na testa e um cachecol grande demais. Quando voc\u00ea encontra a abertura, Flick j\u00e1 encontrou a sa\u00edda.', hp: 93, speed: 1.075, damage: 0.975, stamina: 102, stance: 0.38, spread: 28, idleSpeed: 3.7, idleAmount: 2.9, passive: { id: 'escape', name: 'Fuga perfeita', description: 'Sua esquiva percorre uma dist\u00e2ncia 12% maior.' }, ratings: [5, 1, 1] },
  { id: 'aurex', name: 'AUREX', title: 'Um posto, uma promessa', weapon: 'spear', primary: '#293331', secondary: '#182421', accent: '#b85345', skin: '#b8a38b', outfit: 'armor', accessory: 'red-plates', description: 'Armadura negra marcada em vermelho. A guarda imperial pode ter ca\u00eddo; seu \u00faltimo soldado, n\u00e3o.', hp: 110, speed: 0.94, damage: 1.02, stamina: 103, stance: -0.07, spread: 39, idleSpeed: 1.08, idleAmount: 1.35, passive: { id: 'steadfast', name: 'Posto inabal\u00e1vel', description: 'Sofre 20% menos empurr\u00e3o ao bloquear um ataque.' }, ratings: [2, 5, 5] },
  { id: 'morv', name: 'MORV', title: 'O peso da sombra', weapon: 'axe', primary: '#363b42', secondary: '#222a30', accent: '#91a0a4', skin: '#a49b8a', outfit: 'hood', accessory: 'uneven-steel', description: 'Um capuz pesado esconde a face. Placas assim\u00e9tricas contam uma guerra que ele nunca terminou.', hp: 105, speed: 0.96, damage: 1.015, stamina: 103, stance: 0.42, spread: 42, idleSpeed: 1.15, idleAmount: 2.35, passive: { id: 'twisted', name: 'A\u00e7o retorcido', description: 'A antecipa\u00e7\u00e3o de seus ataques pesados \u00e9 6% mais curta.' }, ratings: [2, 3, 3] },
  { id: 'hex', name: 'HEX', title: 'Precis\u00e3o calculada', weapon: 'gauntlets', primary: '#4e6464', secondary: '#263b3b', accent: '#cf5f51', skin: '#a3aaa0', outfit: 'armor', accessory: 'mechanical', description: 'Visor vermelho, manoplas mec\u00e2nicas e movimentos econ\u00f4micos. Para Hex, hesitar tamb\u00e9m pode ser uma t\u00e9cnica.', hp: 101, speed: 1.005, damage: 0.99, stamina: 106, stance: 0.12, spread: 33, idleSpeed: 2.05, idleAmount: 1.15, passive: { id: 'interrupt', name: 'Interrup\u00e7\u00e3o', description: 'Pode cancelar os primeiros 60 ms de um ataque leve pressionando defesa.' }, ratings: [4, 1, 4] },
  { id: 'cain', name: 'CAIN VOR', title: 'A \u00faltima palavra', weapon: 'sword', primary: '#747c7a', secondary: '#39423f', accent: '#adb5a2', skin: '#bba78e', outfit: 'coat', accessory: 'scar-black-blade', description: 'Sobretudo cinza, cicatriz antiga e uma espada negra. O veterano n\u00e3o precisa dizer quem desfere o \u00faltimo golpe.', hp: 107, speed: 0.965, damage: 1.035, stamina: 101, stance: 0.025, spread: 32, idleSpeed: 1.25, idleAmount: 1.45, passive: { id: 'last-word', name: '\u00daltima palavra', description: 'Seus acertos causam 8% mais dano durante 850 ms ap\u00f3s um parry.' }, ratings: [3, 3, 4] },
];

export const CHARACTER_MAP = new Map(CHARACTERS.map(character => [character.id, character]));
export function getCharacter(id: string) { return CHARACTER_MAP.get(id) || CHARACTERS[0]; }